#gnumake
MAKE_VERSION:=3.81
MAKECMDGOALS:=
NULL:=
space:=$(NULL) $(NULL)

#this is random stuff
BOARD_HAVE_BLUETOOTH_BLUEZ:=
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR:=
BLUETOOTH_HCI_USE_MCT:=
CLEAR_TBLGEN_VARS:=
CLANG_HOST_BUILD_MK:=
CLANG_TBLGEN_RULES_MK:=
LOCAL_INSTALLED_MODULE:=
JNI_H_INCLUDE:=
BOARD_HAS_QCOM_WLAN:=
local_javac_flags:=
BUILD_LIBFFI_TESTS:=
BOARD_HAVE_BLUETOOTH:=true
BUILD_QCGPS:=
SFW_MCU_CONF:=
WK_WTF_USE_SKIA:=
WK_ENABLE_GLIB_SUPPORT:=
DEBUG_BIONIC_LIBC:=
BOARD_MALLOC_ALIGNMENT:=
WITH_MALLOC_CHECK_LIBC_A:=
BUILD_NATIVE_TEST:=
BOARD_HAVE_BLUETOOTH_BCM:=
BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL:=
BOARD_BLUETOOTH_USES_HCIATTACH_PROPERTY:=
HAVE_SELINUX:=
BUILD_CTSCORE_PACKAGE:=dontfail
WITH_HOST_DALVIK:=
NO_FALLBACK_FONT:=
PIXELFLINGER_CFLAGS:=
USE_MINGW:=
INIT_BOOTCHART:=
TARGET_SIMULATOR:=true
TARGET_PRODUCT:=full_x86
TARGET_ARCH:=x86
TARGET_BUILD_VARIANT:=user
HOST_OS:=linux
TARGET_BUILD_APPS:=
BUILD_TINY_ANDROID:=
TARGET_PROVIDES_INIT_RC:=
EXTRA_STATIC_LIBS:=
BOARD_CHARGER_DISABLE_INIT_BLANK:=
BOARD_CHARGER_ENABLE_SUSPEND:=
VERSIONS_CHECKED:=
EMMA_INSTRUMENT_STATIC:=
INTERNAL_VALID_VARIANTS:=

#build system basics
TOP=$(call my-dir)
ANDROID_BUILD_TOP=$(TOP)
PLATFORM_VERSION=4.1.2
PLATFORM_SDK_VERSION=4.1

#compiler
TARGET_CXX=g++

#paths
KERNEL_HEADERS=somewhere/over/the/rainbow
PRODUCT_OUT=out/fix/me/product/out
TARGET_OUT=out/fix/me/target/out
TARGET_OUT_SHARED_LIBRARIES:= $(TARGET_OUT)/lib
TARGET_COPY_OUT_DATA:=data
TARGET_OUT_DATA:=$(PRODUCT_OUT)/$(TARGET_COPY_OUT_DATA)
TARGET_OUT_DATA_APPS:=$(TARGET_OUT_DATA)/app
TARGET_COPY_OUT_ROOT := root
TARGET_ROOT_OUT := $(PRODUCT_OUT)/$(TARGET_COPY_OUT_ROOT)
TARGET_ROOT_OUT_SBIN := $(PRODUCT_OUT)/$(TARGET_COPY_OUT_ROOT)
TARGET_ROOT_OUT_SBIN := $(TARGET_ROOT_OUT)/sbin
TARGET_OUT_UNSTRIPPED := $(PRODUCT_OUT)/symbols
TARGET_ROOT_OUT_UNSTRIPPED := $(PRODUCT_OUT)/symbols/root/
TARGET_ROOT_OUT_SBIN_UNSTRIPPED := $(TARGET_OUT_UNSTRIPPED)/sbin
TARGET_OUT_OPTIONAL_EXECUTABLES:= $(TARGET_OUT)/xbin
TARGET_OUT_INTERMEDIATE_LIBRARIES:= $(TARGET_OUT)/intermediate/libraries
TARGET_SHLIB_SUFFIX := .so
TARGET_EXECUTABLE_SUFFIX := .exe
TARGET_OS := linux
TARGET_OUT_ETC := target/out/etc/
OUT_DIR := out

#host config
HOST_ARCH := x86_64
HOST_OUT_EXECUTABLES=out/fix/me/host/executables
HOST_EXECUTABLE_SUFFIX=.exe

#target config
TARGET_CPU_SMP:=true
ARCH_X86_HAVE_SSE2:=true
ARCH_X86_HAVE_SSSE3:=true
ARCH_ARM_HAVE_NEON:=true
ARCH_ARM_HAVE_TLS_REGISTER:=true
TARGET_ARCH_VARIANT:=x86-intel
TARGET_DEVICE:=wurst

#these are expected to be defined after include $(BUILD_*)
intermediates:=
ALL_MODULES.toolbox.INSTALLED:=
ALL_MODULES.init.INSTALLED:=
LOCAL_BUILT_MODULE=fixme/built/$(LOCAL_MODULE)

include $(NOM_ARG1)
